parent: "config/vis3d/o3d_scene.yml"

body_model:
  module: "easymocap.smplmodel.body_model.SMPLlayer"
  args:
    _no_merge_: True
    model_path: "data/smplx/smplh/MANO_LEFT.pkl"
    model_type: "mano"
    gender: "neutral"
    device: "cuda"
    regressor_path: "data/smplx/J_regressor_mano_LEFT.txt"